"""empty message

Revision ID: 5dcd560413f3
Revises: 12480f40df23
Create Date: 2019-09-11 18:14:19.648231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dcd560413f3'
down_revision = '12480f40df23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('category_name', sa.String(length=80), nullable=True))
    op.create_foreign_key(None, 'article', 'category', ['source_id', 'category_name'], ['source_id', 'name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'category_name')
    # ### end Alembic commands ###
