"""empty message

Revision ID: 660283eabec5
Revises: 1b74b3a3baed
Create Date: 2019-09-18 10:06:39.362281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660283eabec5'
down_revision = '1b74b3a3baed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_keywords',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('textrank_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'keyword_id')
    )
    op.add_column('text_articles', sa.Column('relevance_score', sa.Float(), nullable=True))
    op.add_column('text_keywords', sa.Column('textrank_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text_keywords', 'textrank_score')
    op.drop_column('text_articles', 'relevance_score')
    op.drop_table('article_keywords')
    # ### end Alembic commands ###
