#!/bin/bash

set -e

source config

CONTAINER=$APP-es
AUTH_FILE=$PROJECT_ROOT/.auth

echo "Generate passwords for elasticsearch"
! [[ "$(is_running $CONTAINER )" -gt 0 ]] && echo "$CONTAINER not running" && exit 1
[ -f $AUTH_FILE ] && echo "Authentication file exists" && exit 0

COMMAND="podman exec $CONTAINER bin/elasticsearch-setup-passwords auto --batch > $AUTH_FILE"
echo "$COMMAND"
while true; do
  bash -c "$COMMAND" > /dev/null 2>&1 && { echo "Authentication file is created!" && exit 0 ;}
  echo "ElasticSearch is not ready yet..." && sleep 5
done

