"""empty message

Revision ID: 2e6eaa12af55
Revises: f9e0741270d7
Create Date: 2019-09-19 08:01:40.898986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e6eaa12af55'
down_revision = 'f9e0741270d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('keyword', 'value',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('keyword', 'value',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
    # ### end Alembic commands ###
