"""empty message

Revision ID: f9e0741270d7
Revises: 660283eabec5
Create Date: 2019-09-18 13:01:07.466995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f9e0741270d7'
down_revision = '660283eabec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_keyword',
    sa.Column('input_text_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('textrank_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['input_text_id'], ['input_text.id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], ),
    sa.PrimaryKeyConstraint('input_text_id', 'keyword_id')
    )
    op.create_table('article_keyword',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('textrank_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'keyword_id')
    )
    op.create_table('text_article',
    sa.Column('input_text_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['input_text_id'], ['input_text.id'], ),
    sa.PrimaryKeyConstraint('input_text_id', 'article_id')
    )
    op.drop_table('article_keywords')
    op.drop_table('text_articles')
    op.drop_table('text_keywords')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_keywords',
    sa.Column('input_text_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('keyword_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('textrank_score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['input_text_id'], ['input_text.id'], name='text_keywords_input_text_id_fkey'),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], name='text_keywords_keyword_id_fkey'),
    sa.PrimaryKeyConstraint('input_text_id', 'keyword_id', name='text_keywords_pkey')
    )
    op.create_table('text_articles',
    sa.Column('input_text_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('relevance_score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], name='text_articles_article_id_fkey'),
    sa.ForeignKeyConstraint(['input_text_id'], ['input_text.id'], name='text_articles_input_text_id_fkey'),
    sa.PrimaryKeyConstraint('input_text_id', 'article_id', name='text_articles_pkey')
    )
    op.create_table('article_keywords',
    sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('keyword_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('textrank_score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], name='article_keywords_article_id_fkey'),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], name='article_keywords_keyword_id_fkey'),
    sa.PrimaryKeyConstraint('article_id', 'keyword_id', name='article_keywords_pkey')
    )
    op.drop_table('text_article')
    op.drop_table('article_keyword')
    op.drop_table('text_keyword')
    # ### end Alembic commands ###
